package killbox.game.boxes;

enum BoxStatus
{
    MAIN_FALLING;
    MAIN_CONVEYOR;
    
    LEFT_CONVEYOR;
    LEFT_SLIDING;
    LEFT_WAITING;
    LEFT_PRESSED;
	LEFT_PRESSED_CONVEYOR;
	LEFT_BACK_CONVEYOR;
}