package killbox.game.boxes;

enum BoxStatus
{
    MAIN_FALLING;
    MAIN_CONVEYOR;
	//
    LEFT_CONVEYOR;
    LEFT_SLIDING;
    LEFT_WAITING;
    LEFT_PRESSED;
	LEFT_PRESSED_CONVEYOR;
	//
	LEFT_BACK_CONVEYOR;
	LEFT_BACK_SLIDING;
	LEFT_BACK_WAITING;
	LEFT_BACK_SPRINGING_CORRECT;
	LEFT_BACK_SPRINGING_BACKWARDS;
	//
	RIGHT_FALLING;
	//
	RIGHT_LEFT_CONVEYOR;
	RIGHT_LEFT_CONVEYOR_FALLING;
	//
	RIGHT_RIGHT_CONVEYOR;
	RIGHT_RIGHT_SLIDING;
	RIGHT_RIGHT_WAITING;
	//
	RIGHT_RIGHT_SPIKED;
	RIGHT_RIGHT_SPIKED_CONVEYOR;
	//
	RIGHT_SUCKING;
	//
	TOP_TUBE;
	TOP_SLIDING;
	TOP_WAITING;
	TOP_CONFIRMING;
}